accounts/passwords/urls.py
# accounts.passwords.urls.py 
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
        url(r'^password/change/$', 
                auth_views.PasswordChangeView.as_view(), 
                name='password_change'),
        url(r'^password/change/done/$',
                auth_views.PasswordChangeDoneView.as_view(), 
                name='password_change_done'),
        url(r'^password/reset/$', 
                auth_views.PasswordResetView.as_view(), 
                name='password_reset'),
        url(r'^password/reset/done/$', 
                auth_views.PasswordResetDoneView.as_view(), 
                name='password_reset_done'),
        url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
                auth_views.PasswordResetConfirmView.as_view(), 
                name='password_reset_confirm'),
        url(r'^password/reset/complete/$', 
                auth_views.PasswordResetCompleteView.as_view(), 
                name='password_reset_complete'),
]

accounts/urls.py
from django.conf.urls import url

from products.views import UserProductHistoryView
from .views import (
    AccountHomeView,
    AccountEmailActivateView,
    UserDetailUpdateView
)

urlpatterns = [
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$',
        AccountEmailActivateView.as_view(),
        name='email-activate'),
    url(r'^email/resend-activation/$',
        AccountEmailActivateView.as_view(),
        name='resend-activation'),
]

carts/urls.py
from django.conf.urls import url

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
    payment_response,
    coupon,
    special_checkout_home,
    special_cart,
    disable_coupon
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^supportyourteam/', special_cart, name='special_cart'),

    url(r'^checkout/$', checkout_home, name='checkout'),

    url(r'^supportyourteam-checkout/$', special_checkout_home, name='special_checkout'),

    url(r'^update/$', cart_update, name='update'),
    url(r'^apply_coupon/$', coupon, name='coupon'),
    url(r'^disable_coupon/$', disable_coupon, name='disable_coupon')

]

spograde/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
# from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
import os
from django.views.static import serve

from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticSitemap
from products.sitemaps import ProductSitemap
from django.views.generic import TemplateView

from accounts.views import LoginView, RegisterView, GuestRegisterView
from addresses.views import (
    AddressCreateView,
    AddressListView,
    AddressUpdateView,
    checkout_address_create_view, 
    checkout_address_reuse_view
    )
from analytics.views import SalesView, SalesAjaxView
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from orders.views import LibraryView

from products.views import category_view

from carts.views import payment_response

from verification.views import ProductVerificationView

from .views import home_page, about_page, subscribe, ipl_landing_page, intellectual_property, contact_page, shipping_policy, disclaimer, payment_partners,refund_return_policy,term_of_use,privacy_policy,faq

sitemaps = {
    'pages': StaticSitemap,
    'product': ProductSitemap
}

urlpatterns = [
    # Overall website URL structure
    url(r'^$', home_page, name='home'),
    url('sitemap.xml', sitemap, {'sitemaps' : sitemaps } , name='django.contrib.sitemaps.views.sitemap'),
    url('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    url(r'^about/$', about_page, name='about'),
    url(r'^terms-of-use/$', term_of_use, name='term_of_use'),
    url(r'^privacy-policy/$', privacy_policy, name='privacy_policy'),
    url(r'^return-refund-cancellation-policy/$', refund_return_policy, name='return_refund_policy'),    
    url(r'^faq/$', faq, name='faq'),
    url(r'^intellectual-property/$', intellectual_property, name='intellectual_property'),
    url(r'^shipping-policy/$', shipping_policy, name='shipping_policy'),
    url(r'^disclaimer/$', disclaimer, name='disclaimer'),
    # url(r'^payment-partners/$', payment_partners, name='payment_partners'),

    url(r'^supportyourteam2020/$', ipl_landing_page, name='ipl_landing_page'),

    
    url('summernote/', include('django_summernote.urls')),


    #url(r'^accounts/login/$', RedirectView.as_view(url='/login')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls", namespace='account')),
    
    # url(r'^', include("verification.urls", namespace='verification')),

    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    url(r'^analytics/sales/$', SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^subscribe/$', subscribe, name='subscribe'),
    url(r'^login/$', LoginView.as_view(), name='login'),

    url(r'^product-verification/$', ProductVerificationView.as_view(), name='product-verification'),


    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    
    url(r'^paytm/response/', payment_response, name='payment_response'),

    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    # url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    # url(r'^library/$', LibraryView.as_view(), name='library'),

    url(r'^category/(?P<slug>[\w-]+)/$', category_view, name='detail'),
    
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^spograde-admin/', admin.site.urls), # Admin Panel Change according to your configuration
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.views.generic.edit import FormMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.contrib import messages
from spograde.mixins import NextUrlMixin, RequestFormAttachMixin
from .forms import LoginForm, RegisterForm, GuestForm, ReactivateEmailForm, UserDetailChangeForm
from .models import GuestEmail, EmailActivation
from .signals import user_logged_in


# LoginRequiredMixin,
class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'

    def get_object(self):
        return self.request.user


class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None

    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Your email has been confirmed. Please login.")
                return redirect("login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Your email has already been confirmed
                    Do you need to <a href="{link}">reset your password</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("login")
        context = {'form': self.get_form(), 'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = """Activation link sent, please check your email."""
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key}
        return render(self.request, 'registration/activation-error.html', context)


class GuestRegisterView(NextUrlMixin, RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/register/'

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)


class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)


class RegisterView(SuccessMessageMixin, CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_message = "Please check your mail for activation."
    success_url = '/login/'


class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Change Your Account Details'
        return context

    def get_success_url(self):
        return reverse("account:home")

# def login_page(request):
#     form = LoginForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     next_ = request.GET.get('next')
#     next_post = request.POST.get('next')
#     redirect_path = next_ or next_post or None
#     if form.is_valid():
#         username  = form.cleaned_data.get("username")
#         password  = form.cleaned_data.get("password")
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             try:
#                 del request.session['guest_email_id']
#             except:
#                 pass
#             if is_safe_url(redirect_path, request.get_host()):
#                 return redirect(redirect_path)
#             else:
#                 return redirect("/")
#         else:
#             # Return an 'invalid login' error message.
#             print("Error")
#     return render(request, "accounts/login.html", context)

# User = get_user_model()
# def register_page(request):
#     form = RegisterForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     if form.is_valid():
#         form.save()
#     return render(request, "accounts/register.html", context)

accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}
{% block title %} Update Account Details - Spograde {% endblock %}
{% block content %}

<div class="holder mt-0">
            <div class="container">
                <ul class="breadcrumbs">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><span>My account</span></li>
                </ul>
            </div>
        </div><br/>
        <div class="holder mt-0">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 aside aside--left">
                         <div class="list-group"><a href="/account" class="list-group-item">Account Details</a> 
                        <a href="{% url "billing-payment-method" %}" class="list-group-item">Payment Methods</a> 
                        <a href="{% url "addresses" %}" class="list-group-item">Addresses</a> 
                        <a href="{% url "password_change" %}" class="list-group-item">Change Password</a> 
                        <a href="{% url "orders:list" %}" class="list-group-item">Order History</a> 
                        <a href="{% url "account:user-update" %}" class="list-group-item active">Update Details</a> 
                        {% comment %} <a href="#" class="list-group-item">Compare Products</a> {% endcomment %}</div>
                    </div>
                    <div class="col-md-9 aside">
                        {% comment %} <h2>Account Details</h2> {% endcomment %}
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-body">
                                        {% if title %} <h3>{{ title }}</h3> {% endif %}

                                        <form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
                                        {% if next_url %}
                                        <input type='hidden' name='next' value='{{ next_url }}' />
                                        {% endif %}
                                      {{ form.as_p }}
                                      <label for='email'>Email</label>
                                      <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /><span class='help-text'>Cannot change email</span><br/>
                                      <button type='submit' class='btn btn-default my-3'>Save</button>
                                      <a href='{% url "password_change" %}'>Change Password</a>
                                    </form>

                                        
                                    </div>
                                </div>
                            </div>
                        </div>             
                    </div>
                </div>
            </div>
        </div>
    </div><br/>
</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}
{% block title %} Account - Spograde {% endblock %}
{% block content %}
<div class="holder mt-0">
            <div class="container">
                <ul class="breadcrumbs">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><span>My account</span></li>
                </ul>
            </div>
        </div><br/>
        <div class="holder mt-0">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 aside aside--left">
                        <div class="list-group"><a href="/account" class="list-group-item active">Account Details</a> 
                        <a href="{% url "billing-payment-method" %}" class="list-group-item">Payment Methods</a> 
                        <a href="{% url "addresses" %}" class="list-group-item">Addresses</a> 
                        <a href="{% url "password_change" %}" class="list-group-item">Change Password</a> 
                        <a href="{% url "orders:list" %}" class="list-group-item">Order History</a> 
                        <a href="{% url "account:user-update" %}" class="list-group-item">Update Details</a> 
                        {% comment %} <a href="#" class="list-group-item">Compare Products</a> {% endcomment %}</div>
                    </div>
                    <div class="col-md-9 aside">
                        <h2>Account Details</h2>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h3>Personal Info</h3>
                                        <p><b>First Name:</b> {{ request.user.full_name }}<br><b>E-mail:</b> {{ request.user.email }} <br><b>Phone:</b> {{ request.user.phone }} </p>
                                        <div class="mt-2 clearfix"><a href="{% url "account:user-update" %}" class="link-icn"><i class="icon-pencil"></i>Update Details</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>             
                    </div>
                </div>
            </div>
        </div>
    </div><br/>


{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block title %} Account Login - Spograde {% endblock %}
{% block content %}

<div class="holder mt-0">
            <div class="container">
                <ul class="breadcrumbs">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><span>Login</span></li>
                </ul>
            </div>
        </div>
        <div class="holder mt-0">
            <div class="container">
                <div class="row justify-content-around">
                    <div class="col-sm-6 col-md-4">
                        <div id="loginForm">
                            <h2 class="text-center">SIGN IN</h2>
                            <div class="form-wrapper">
                                {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                                {% endfor %}
                                <p>If you have an account with us, please log in.</p>
                                    <form method='POST'> {% csrf_token %}
                                    <div class="form-group">{{ form }}</div>
                                    <p class="text-uppercase"><a href="/accounts/password/reset/">Forgot Your Password?</a></p>
                                    <div class="clearfix"><input id="checkbox1" name="checkbox1" type="checkbox" checked="checked"> 
                                    <label for="checkbox1">Remember me</label></div>
                                    <button type='submit' class='btn'>Sign In</button>
                                  </form>
                            </div>
                        </div>
                        <div id="recoverPasswordForm" class="d-none">
                            <h2 class="text-center">RESET YOUR PASSWORD</h2>
                            <div class="form-wrapper">
                                <p>We will send you an email to reset your password.</p>
                                <form action="#">
                                    <div class="form-group"><input type="text" class="form-control" placeholder="Your Name"></div>
                                    <div class="form-group"><input type="password" class="form-control" placeholder="Password"></div>
                                    <div class="btn-toolbar"><a href="#" class="btn btn--alt js-toggle-forms">Cancel</a> <button class="btn ml-1">Submit</button></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-divider"></div>
                    <div class="col-sm-6 col-md-4 mt-3 mt-sm-0">
                        <h2 class="text-center">REGISTER</h2>
                        <div class="form-wrapper">
                            <p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p><a href="{% url 'register' %}" class="btn">create an account</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% block title %} Account Register - Spograde {% endblock %}
{% block content %}

      <div class="holder mt-0">
            <div class="container">
                <ul class="breadcrumbs">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><span>Create account</span></li>
                </ul>
            </div>
        </div>
        <div class="holder mt-0">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-8 col-md-6">
                        <h2 class="text-center">CREATE AN ACCOUNT</h2>
                        <div class="form-wrapper">
                            <p>To access your whishlist, address book and contact preferences and to take advantage of our speedy checkout, create an account with us now.</p>
                             <form method='POST'> {% csrf_token %}
                             <div class="form-group"> {{ form }} </div>
                              <div class="clearfix"><input id="checkbox1" name="checkbox1" type="checkbox" checked="checked"> <label for="checkbox1">By registering your details you agree to our Terms and Conditions and privacy and cookie policy</label></div>
                              <div class="text-center"><button type='submit' class='btn'>Register Now</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
{% endblock %}